name: cadastro_pessoa
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  path: any
  flutter:
    sdk: flutter
  http: ^1.2.0
  brasil_fields: ^1.14.3
  cupertino_icons: ^1.0.6
  pull_down_button: ^0.9.3
  flutter_bloc: ^8.1.6
  rxdart: ^0.28.0
  equatable: ^2.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  test: ^1.25.7
  mockito: ^5.4.4
  build_runner: ^2.4.12
  bloc_test: ^9.1.7
  

flutter:

  uses-material-design: true

  